---
name: Remove needinfo label

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'status: needs information') &&
      github.event.comment.author_association != 'OWNER' &&
      github.event.comment.author_association != 'MEMBER' &&
      github.event.comment.author_association != 'COLLABORATOR'
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: App token generate
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        if: ${{ vars.APP_CLIENT_ID }}
        id: app-token
        with:
          app-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Remove needinfo label and add answered label
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ steps.app-token.outputs.token || github.token }}
        run: |
          gh issue edit $ISSUE_NUMBER --repo "$GITHUB_REPOSITORY" --remove-label "status: needs information" --add-label "status: answered"
