---
name: Remove needinfo label

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'status: needs information') &&
      github.event.comment.author_association != 'OWNER' &&
      github.event.comment.author_association != 'MEMBER' &&
      github.event.comment.author_association != 'COLLABORATOR'
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Remove needinfo label and add answered label
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue edit $ISSUE_NUMBER --remove-label "status: needs information" --add-label "status: answered"
